//! ICU4XFixedDecimalFormatterOptions generated by diplomat
const std = @import("std");
pub const diplomat_runtime = @import("diplomat_runtime.zig");

pub const ICU4XFixedDecimalGroupingStrategy = @import("ICU4XFixedDecimalGroupingStrategy.zig");
const zapi = @This();

pub const ICU4XFixedDecimalFormatterOptions = extern struct {
    grouping_strategy: ICU4XFixedDecimalGroupingStrategy,
    some_other_config: bool,
};

pub extern fn ICU4XFixedDecimalFormatterOptions_default() ICU4XFixedDecimalFormatterOptions;
pub extern fn ICU4XFixedDecimalFormatterOptions_destroy(self: *ICU4XFixedDecimalFormatterOptions) void;
