//! ICU4XDataProvider generated by diplomat
const std = @import("std");
pub const diplomat_runtime = @import("diplomat_runtime.zig");

const zapi = @This();

pub const ICU4XDataProvider = opaque{};
pub const diplomat_result_void_void = @import("diplomat_result_void_void.zig");

pub extern fn ICU4XDataProvider_new_static() *ICU4XDataProvider;

pub extern fn ICU4XDataProvider_returns_result() diplomat_result_void_void;
pub extern fn ICU4XDataProvider_destroy(self: *ICU4XDataProvider) void;

