//! ICU4XFixedDecimal generated by diplomat
const std = @import("std");
pub const diplomat_runtime = @import("diplomat_runtime.zig");

const zapi = @This();

pub const ICU4XFixedDecimal = opaque {};
pub const diplomat_result_void_void = @import("diplomat_result_void_void.zig");

pub extern fn ICU4XFixedDecimal_new(v: i32) *ICU4XFixedDecimal;

pub extern fn ICU4XFixedDecimal_multiply_pow10(self: *ICU4XFixedDecimal, power: i16) void;

pub extern fn ICU4XFixedDecimal_to_string(self: ?*const ICU4XFixedDecimal, to: ?*diplomat_runtime.DiplomatWriteable) diplomat_result_void_void.diplomat_result_void_void;
pub extern fn ICU4XFixedDecimal_destroy(self: *ICU4XFixedDecimal) void;
