//! ICU4XFixedDecimalGroupingStrategy generated by diplomat
const std = @import("std");
pub const diplomat_runtime = @import("diplomat_runtime.zig");

const zapi = @This();

pub const ICU4XFixedDecimalGroupingStrategy = union(enum) {
    ICU4XFixedDecimalGroupingStrategy_Auto: 0,
    ICU4XFixedDecimalGroupingStrategy_Never: 1,
    ICU4XFixedDecimalGroupingStrategy_Always: 2,
    ICU4XFixedDecimalGroupingStrategy_Min2: 3,
};

pub extern fn ICU4XFixedDecimalGroupingStrategy_destroy(self: *ICU4XFixedDecimalGroupingStrategy) void;
