//! ICU4XFixedDecimalFormatter generated by diplomat
const std = @import("std");
pub const diplomat_runtime = @import("diplomat_runtime.zig");
pub const ICU4XLocale = @import("ICU4XLocale.zig");
const ICU4XDataProvider = @import("ICU4XDataProvider.zig");
const ICU4XFixedDecimal = @import("ICU4XFixedDecimal.zig");

const zapi = @This();

pub const ICU4XFixedDecimalFormatter = opaque {};
const ICU4XFixedDecimalFormatterOptions = @import("ICU4XFixedDecimalFormatterOptions.zig");
const fmt_void = @import("diplomat_result_box_ICU4XFixedDecimalFormatter_void.zig");

pub extern fn ICU4XFixedDecimalFormatter_try_new(locale: ?*ICU4XLocale.ICU4XLocale, provider: ?*ICU4XDataProvider.ICU4XDataProvider, options: ICU4XFixedDecimalFormatterOptions.ICU4XFixedDecimalFormatterOptions) fmt_void.diplomat_result_box_ICU4XFixedDecimalFormatter_void;

pub extern fn ICU4XFixedDecimalFormatter_format_write(self: ?*const ICU4XFixedDecimalFormatter, value: ?*const ICU4XFixedDecimal.ICU4XFixedDecimal, write: ?*diplomat_runtime.DiplomatWriteable) void;
pub extern fn ICU4XFixedDecimalFormatter_destroy(self: ?*ICU4XFixedDecimalFormatter) void;
